#!/usr/bin/env python3
import smtplib  
import sys
import email.utils
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

SENDER = 'sender@example.com'  
SENDERNAME = 'Sender Name'
RECIPIENT  = 'recipient@example.com'
USERNAME_SMTP = "smtp_username"
PASSWORD_SMTP = "smtp_password"
HOST = "email-smtp.us-east-1.amazonaws.com"
PORT = 587

SUBJECT = 'Notification'

BODY_HTML = """<html>
<head></head>
<body>
  <h1>Sample email</h1>
  <p>Sample test.</p>
</body>
</html>
"""

# Create message container - the 
msg = MIMEMultipart('alternative')  # correct MIME is multipart/alternative
msg['Subject'] = SUBJECT
msg['From'] = email.utils.formataddr((SENDERNAME, SENDER))
msg['To'] = RECIPIENT
print(f'Sending message to {msg["To"]} from {msg["From"]}: {msg["Subject"]} ...')

# msg.attach(MIMEText("plain text message", 'plain'))
msg.attach(MIMEText(BODY_HTML, 'html'))
try:  
    server = smtplib.SMTP(HOST, PORT)
    server.ehlo()
    server.starttls()
    #stmplib docs recommend calling ehlo() before & after starttls()
    server.ehlo()
    server.login(USERNAME_SMTP, PASSWORD_SMTP)
    server.sendmail(SENDER, RECIPIENT, msg.as_string())
    server.close()
except Exception as e:
    print("Error: ", e)
    sys.exit(1)
else:
    print("Email sent!")
