name: Build and deploy
on:
  push: {branches: develop}
  workflow_dispatch: {}

jobs:

  build-deploy-webapp:
    name: Build and Deploy CV19 WebApp
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    env:
      DEBUG: ${{ secrets.DEBUG }}
      BUILD_LOG: /tmp/build-${{ github.run_id }}.log
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v2
      - name: Fetch the whole git history (including tags)
        run: git fetch --prune --unshallow
      - name: Show last commits
        env:
          COMMITS_COUNT: 5
        run: |
          set -o pipefail
          (echo "Last commits in ${{github.repository}}"; git log --oneline -n ${COMMITS_COUNT} 2>&1; echo "--------------------") | tee "${BUILD_LOG}"
      - name: Install dependencies
        run: |
          set -o pipefail
          (echo "Install dependencies"; npm install 2>&1; echo "--------------------") | tee -a "${BUILD_LOG}"
      - name: Build
        run: |
          export BUILD_NUMBER=${GITHUB_RUN_NUMBER}
          set -o pipefail
          (echo "Build ${{github.repository}} (BUILD_NUMBER=${BUILD_NUMBER})"; npm run build 2>&1; echo "--------------------") | tee -a "${BUILD_LOG}"
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          export S3_BUCKET="${{ secrets.DEV_S3_BUCKET }}"
          # echo "S3_BUCKET=$(echo "${S3_BUCKET}" | sed -e 's/\(.\)/\1_/g'))"
          echo "Show bucket's content"
          aws s3 ls s3://${S3_BUCKET}/
          echo "Upload test file"
          echo "Test file" > ./test.txt
          date >> ./test.txt
          aws s3 cp ./test.txt s3://${S3_BUCKET}/
          echo "Show bucket's content 2"
          aws s3 ls s3://${S3_BUCKET}/
          echo "Delete file"
          aws s3 rm s3://${S3_BUCKET}/test.txt
          echo "."
          set -o pipefail
          (echo "Deploy static site from ${{github.repository}}"; npm run deploy -- --silent 2>&1; echo "--------------------") | tee -a "${BUILD_LOG}"
      - name: Send notification
        if: ${{ always() }}
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_FROM_EMAIL: ${{ secrets.SMTP_FROM_EMAIL }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          JOB_STATUS: ${{ job.status }}
        run: |
          branch=$(echo "${{github.ref}}" | sed 's/^refs\/heads\///g')
          grep -v '^[[:space:]]*$' "${BUILD_LOG}" \
          | ../scripts/smtpsender "[${{ github.repository }}] Run ${JOB_STATUS}: ${{github.workflow}} - ${branch}."
